stages:
  - build
  - paks

image: archlinux/archlinux:base-devel

archiso:
  tags:
    - build
  stage: build
  script:
    - ./ci.build.sh
  artifacts:
    paths:
      - out/*.iso
    expire_in: 1 week
