#!/bin/sh

set -e

# OrangePi NEO-01 Screen Rotation Quirk
if [[ $(cat /sys/devices/virtual/dmi/id/product_name) == "NEO-01" && \
    $(cat /sys/devices/virtual/dmi/id/sys_vendor) == "OrangePi" ]]; then
    # Rotate the builtin screen every time so it's the right way around.
    xrandr --output "$(xrandr -q | grep eDP | cut -d" " -f1)" --rotate "right"
fi
